
###
# @name: TokenExchange
POST {{token_uri}}
Content-Type: application/x-www-form-urlencoded

grant_type = authorization_code &
client_id = {{clientId}} &
code = {{code}} &
redirect_uri = {{redirect_uri}} &
code_verifier = {{code_verifier}}
